#' Function to order country name
#'
#' @param x Character vector with country names
#'
#' @examples
#' align_country_name(c("US", "UK", "Россия")) ## returns c("USA", "United Kingdom", "Russia")
#'
#'
#' @import stringr
#' @import purrr
#'




#' @export
align_country_name <- function(x) {

  stopifnot(is.character(x))

  countries <- tribble(
    ~name, ~synonym,
    "Abkhazia", "Abkhazia",
    "Afghanistan", "Afghanistan",
    "Albania", "Albania",
    "Algeria", "Algeria",
    "Andorra", "Andorra",
    "Angola", "Angola",
    "Argentina", "Argentina",
    "Armenia", "Armenia",
    "Aruba (Netherlands)", "Aruba (Netherlands)",
    "Aruba (Netherlands)", "Aruba",
    "Australia", "Australia",
    "Austria", "Austria",
    "Azerbaijan", "Azerbaijan",
    "Bahamas", "Bahamas",
    "Bahrain", "Bahrain",
    "Bangladesh", "Bangladesh",
    "Barbados", "Barbados",
    "Belarus", "Belarus",
    "Belgium", "Belgium",
    "Belize", "Belize",
    "Benin", "Benin",
    "Bermuda (United Kingdom)", "Bermuda (United Kingdom)",
    "Bermuda (United Kingdom)", "Bermuda",
    "Bolivia", "Bolivia",
    "Bosnia and Herzegovina", "Bosnia and Herzegovina",
    "Botswana", "Botswana",
    "Brazil", "Brazil",
    "Brunei", "Brunei",
    "Bulgaria", "Bulgaria",
    "Bhutan", "Bhutan",
    "Burkina Faso", "Burkina Faso",
    "Burundi", "Burundi",
    "Cambodia", "Cambodia",
    "Cameroon", "Cameroon",
    "Canada", "Canada",
    "Cape Verde", "Cape Verde",
    "Cape Verde", "Cabo Verde",
    "Cape Verde", "Republic of Cabo Verd",
    "Central African Republic", "Central African Republic",
    "Central African Republic", "CAR",
    "Chad", "Chad",
    "Chile", "Chile",
    "China", "China",
    "Colombia", "Colombia",
    "Comoros", "Comoros",
    "Costa Rica", "Costa Rica",
    "Croatia", "Croatia",
    "Cuba", "Cuba",
    "Czech Republic", "Czech Republic",
    "Cyprus", "Cyprus",
    "Democratic Republic of the Congo", "Democratic Republic of the Congo",
    "Democratic Republic of the Congo", "Republic of the Congo",
    "Denmark", "Denmark",
    "Djibouti", "Djibouti",
    "Dominica", "Dominica",
    "Dominican Republic", "Dominican Republic",
    "East Timor", "East Timor",
    "East Timor", "Timor-Leste",
    "East Timor", "Democratic Republic of Timor-Leste",
    "Ecuador", "Ecuador",
    "Egypt", "Egypt",
    "El Salvador", "El Salvador",
    "Equatorial Guinea", "Equatorial Guinea",
    "Eritrea", "Eritrea",
    "Estonia", "Estonia",
    "Eswatini", "Eswatini",
    "Ethiopia", "Ethiopia",
    "Fiji", "Fiji",
    "Finland", "Finland",
    "France", "France",
    "Gabon", "Gabon",
    "Gambia", "Gambia",
    "Georgia", "Georgia",
    "Germany", "Germany",
    "Ghana", "Ghana",
    "Greece", "Greece",
    "Grenada", "Grenada",
    "Guatemala", "Guatemala",
    "Guinea", "Guinea",
    "Guinea-Bissau", "Guinea-Bissau",
    "Guyana", "Guyana",
    "Haiti", "Haiti",
    "Honduras", "Honduras",
    "Hong Kong (China)", "Hong Kong",
    "Hong Kong (China)", "Hong Kong (China)",
    "Hungary", "Hungary",
    "Iceland", "Iceland",
    "India", "India",
    "Indonesia", "Indonesia",
    "Iran", "Iran",
    "Iraq", "Iraq",
    "Ireland", "Ireland",
    "Israel", "Israel",
    "Italy", "Italy",
    "Ivory Coast", "Ivory Coast",
    "Jamaica", "Jamaica",
    "Japan", "Japan",
    "Jordan", "Jordan",
    "Kazakhstan", "Kazakhstan",
    "Kenya", "Kenya",
    "Kiribati", "Kiribati",
    "Kosovo", "Kosovo",
    "Kuwait", "Kuwait",
    "Kyrgyzstan", "Kyrgyzstan",
    "Kyrgyzstan", "Kyrgyz Republic",
    "Kyrgyzstan", "Kirghizia",
    "Laos", "Laos",
    "Latvia", "Latvia",
    "Lebanon", "Lebanon",
    "Lesotho", "Lesotho",
    "Liechtenstein", "Liechtenstein",
    "Liberia", "Liberia",
    "Libya", "Libya",
    "Lithuania", "Lithuania",
    "Luxembourg", "Luxembourg",
    "Madagascar", "Madagascar",
    "Marshall Islands", "Marshall Islands",
    "Mauritania", "Mauritania",
    "Mauritius", "Mauritius",
    "Malaysia", "Malaysia",
    "Maldives", "Maldives",
    "Mali", "Mali",
    "Malawi", "Malawi",
    "Malta", "Malta",
    "Mexico", "Mexico",
    "Macau (China)", "Macau (China)",
    "Macau (China)", "Macau",
    "Macau (China)", "Macao",
    "Monaco", "Monaco",
    "Moldova", "Moldova",
    "Mongolia", "Mongolia",
    "Morocco", "Morocco",
    "Mozambique", "Mozambique",
    "Myanmar", "Myanmar",
    "Myanmar", "Burma",
    "Myanmar", "Burma (Myanmar)",
    "Namibia", "Namibia",
    "Nauru", "Nauru",
    "Nepal", "Nepal",
    "Netherlands", "Netherlands",
    "New Zealand", "New Zealand",
    "Niger", "Niger",
    "Nigeria", "Nigeria",
    "Nicaragua", "Nicaragua",
    "North Korea", "North Korea",
    "North Macedonia", "Macedonia",
    "North Macedonia", "North Macedonia",
    "Northern Cyprus", "Northern Cyprus",
    "Norway", "Norway",
    "Oman", "Oman",
    "Pakistan", "Pakistan",
    "Palau", "Palau",
    "Panama", "Panama",
    "Papua New Guinea", "Papua New Guinea",
    "Paraguay", "Paraguay",
    "Peru", "Peru",
    "Philippines", "Philippines",
    "Poland", "Poland",
    "Portugal", "Portugal",
    "Qatar", "Qatar",
    "Romania", "Romania",
    "Russia", "Russia",
    "Russia", "Russian Federation",
    "Russia", "Россия",
    "Russia", "РФ",
    "Rwanda", "Rwanda",
    "Rwanda", "Ruanda",
    "Sahrawi Arab Democratic Republic", "Sahrawi Arab Democratic Republic",
    "Saudi Arabia", "Saudi Arabia",
    "Senegal", "Senegal",
    "Serbia", "Serbia",
    "Singapore", "Singapore",
    "Sierra Leone", "Sierra Leone",
    "Slovakia", "Slovakia",
    "Slovenia", "Slovenia",
    "South Africa", "South Africa",
    "South Korea", "South Korea",
    "Spain", "Spain",
    "Sri Lanka", "Sri Lanka",
    "Sweden", "Sweden",
    "Switzerland", "Switzerland",
    "Somaliland", "Somaliland",
    "Suriname", "Suriname",
    "Syria", "Syria",
    "Taiwan", "Taiwan",
    "Tanzania", "Tanzania",
    "Tajikistan", "Tajikistan",
    "Thailand", "Thailand",
    "Togo", "Togo",
    "Togo", "Togolese Republic",
    "Trinidad and Tobago", "Trinidad and Tobago",
    "Tunisia", "Tunisia",
    "Turkey", "Turkey",
    "Uganda", "Uganda",
    "Ukraine", "Ukraine",
    "United Arab Emirates", "United Arab Emirates",
    "United Kingdom", "United Kingdom",
    "United Kingdom", "UK",
    "Uruguay", "Uruguay",
    "USA", "USA",
    "USA", "US",
    "USA", "United States",
    "USA", "США",
    "Venezuela", "Venezuela",
    "Vietnam", "Vietnam",
    "Zambia", "Zambia"
  )

  tibble(
    synonym = x
  ) %>%
    left_join(countries, by = c("synonym")) %>%
    pull(name)

}


